<h1 style="text-align: center;">Used Car Price Prediction - Syarah.com</h1>
<h3 style="text-align: center;">Athiyyah Nisrina Husna & Firsa Adam</h3>

---

## **Section 0. Setup**

### **0.1 Import Library**

In [43]:
import numpy as np
import pandas as pd

pd.set_option('display.max_columns', None)

###  **0.2 Global Configuration**

In [44]:
df = pd.read_csv('../data/raw/UsedCarsSA_Unclean_EN.csv')

## **Section 1. Data Explanation**

(Dataset source: https://www.kaggle.com/datasets/turkibintalib/saudi-arabia-used-cars-dataset)

Note: Setiap baris merepresentasikan satu listing/iklan mobil bekas yang dijual di platform Syarah.com pada tahun 2021.

### **1.1 General Information**

In [45]:
df.head()

,Link,Make,Type,Year,Origin,Color,Options,Engine_Size,Fuel_Type,Gear_Type,Condition,Mileage,Region,Price,Negotiable
0,https://syarah.com/%D9%83%D8%B1%D8%A7%D9%8A%D8...,Chrysler,C300,2018,Saudi,Black,Full,5.7,Gas,Automatic,Used,103000,Riyadh,114000,False
1,https://syarah.com/%D9%86%D9%8A%D8%B3%D8%A7%D9...,Nissan,Patrol,2016,Saudi,White,Full,4.8,Gas,Automatic,Used,5448,Riyadh,Negotiable,True
2,https://syarah.com/online/%D9%86%D9%8A%D8%B3%D...,Nissan,Sunny,2019,Saudi,Silver,Standard,1.5,Gas,Automatic,Used,72418,Riyadh,27500,False
3,https://syarah.com/online/%D9%87%D9%88%D9%86%D...,Hyundai,Elantra,2019,Saudi,Grey,Standard,1.6,Gas,Automatic,Used,114154,Riyadh,43000,False
4,https://syarah.com/online/%D9%87%D9%88%D9%86%D...,Hyundai,Elantra,2019,Saudi,Silver,Semi Full,2.0,Gas,Automatic,Used,41912,Riyadh,59500,False

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8248 entries, 0 to 8247
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Link         8248 non-null   object
 1   Make         8248 non-null   object
 2   Type         8248 non-null   object
 3   Year         8248 non-null   int64
 4   Origin       8153 non-null   object
 5   Color        8248 non-null   object
 6   Options      8139 non-null   object
 7   Engine_Size  5982 non-null   float64
 8   Fuel_Type    8248 non-null   object
 9   Gear_Type    8174 non-null   object
 10  Condition    8248 non-null   object
 11  Mileage      8248 non-null   int64
 12  Region       8248 non-null   object
 13  Price        8248 non-null   object
 14  Negotiable   8248 non-null   bool
dtypes: bool(1), float64(1), int64(2), object(11)
memory usage: 910.3+ KB

In [47]:
df.shape

(8248, 15)

In [48]:
for col in df.columns:
    print(f'===== {col} =====')
    print(df[col].value_counts(dropna=False))
    print()

===== Link =====
Link
https://syarah.com/%D8%AA%D9%88%D9%8A%D9%88%D8%AA%D8%A7_%D8%A8%D8%B1%D8%A7%D8%AF%D9%88_TXL_%D8%B3%D8%B9%D9%88%D8%AF%D9%8A_2015_%D9%86%D8%B5_%D9%81%D9%84/car-10413495                                2
https://syarah.com/%D9%87%D9%88%D9%86%D8%AF%D8%A7%D9%8A_%D8%A7%D9%84%D9%86%D8%AA%D8%B1%D8%A7_GL_%D8%B3%D8%B9%D9%88%D8%AF%D9%8A_2016_%D8%B3%D8%AA%D8%A7%D9%86%D8%AF%D8%B1/car-10457116                2
https://syarah.com/%D8%B4%D9%8A%D9%81%D8%B1%D9%88%D9%84%D9%8A%D9%87_%D8%A7%D9%85%D8%A8%D8%A7%D9%84%D8%A7_2016_%D8%AE%D9%84%D9%8A%D8%AC%D9%8A_LS_%D8%B3%D8%AA%D8%A7%D9%86%D8%AF%D8%B1/car-10448014    2
https://syarah.com/%D9%81%D9%88%D8%B1%D8%AF_%D8%A7%D9%83%D8%B3%D8%A8%D9%84%D9%88%D8%B1_2016_%D8%AE%D9%84%D9%8A%D8%AC%D9%8A_%D8%B3%D8%AA%D8%A7%D9%86%D8%AF%D8%B1/car-10442037                         2
https://syarah.com/%D8%AA%D9%88%D9%8A%D9%88%D8%AA%D8%A7_%D9%83%D8%A7%D9%85%D8%B1%D9%8A_2016_%D8%AE%D9%84%D9%8A%D8%AC%D9%8A_%D8%B3%D8%AA%D8%A7%D9%86%D8%AF%D8%B1/car-10453074                         2
                                                                                                                                                                                                    ..
https://syarah.com/%D8%AA%D9%88%D9%8A%D9%88%D8%AA%D8%A7_%D9%83%D8%A7%D9%85%D8%B1%D9%8A_GL_%D8%B3%D8%B9%D9%88%D8%AF%D9%8A_2017_%D8%B3%D8%AA%D8%A7%D9%86%D8%AF%D8%B1/car-10401729                      1
https://syarah.com/%D9%87%D9%85%D8%B1_%D8%A7%D8%AA%D8%B4_3_2006_%D9%84%D9%84%D8%A8%D9%8A%D8%B9/car-10413367                                                                                          1
https://syarah.com/%D9%87%D9%88%D9%86%D8%AF%D8%A7%D9%89_%D8%B3%D9%88%D9%86%D8%A7%D8%AA%D8%A7_2012/car-10411459                                                                                       1
https://syarah.com/%D9%81%D9%88%D8%B1%D8%AF_%D8%A7%D9%83%D8%B3%D8%A8%D9%84%D9%88%D8%B1%D8%B1_2009_%D9%84%D9%84%D8%A8%D9%8A%D8%B9/car-10264197                                                        1
https://syarah.com/online/%D9%87%D9%88%D9%86%D8%AF%D8%A7%D9%8A_%D8%A7%D9%84%D9%86%D8%AA%D8%B1%D8%A7_GL_2019_%D8%B3%D8%AA%D8%A7%D9%86%D8%AF%D8%B1/car-73118                                           1
Name: count, Length: 8228, dtype: int64

===== Make =====
Make
Toyota          2074
Hyundai          952
Ford             779
Chevrolet        672
Nissan           552
                ...
Lifan              1
Iveco              1
Victory Auto       1
MAN                1
Buick              1
Name: count, Length: 65, dtype: int64

===== Type =====
Type
Land Cruiser    374
Camry           332
Hilux           292
Accent          254
Yukon           231
               ...
XC90              1
Big Truck         1
Galant            1
Trafic            1
Carry             1
Name: count, Length: 435, dtype: int64

===== Year =====
Year
2016    1218
2015     832
2017     819
2018     775
2019     643
2014     572
2020     567
2013     519
2012     325
2011     264
2010     219
2008     203
2021     192
2009     177
2007     176
2006     149
2005      88
2004      70
2003      62
2002      56
1999      43
2001      39
1997      28
1998      27
2000      26
1995      22
1993      15
1991      12
1994      12
1990      12
1996      10
1992       9
1989       8
1983       8
1982       6
1988       5
1987       4
1978       4
1986       4
1985       4
1984       3
1981       3
1980       3
2022       2
1979       2
1977       2
1936       1
1964       1
1963       1
1965       1
1972       1
1970       1
1975       1
1968       1
1961       1
Name: count, dtype: int64

===== Origin =====
Origin
Saudi          6084
Other          1045
Gulf Arabic    1024
NaN              95
Name: count, dtype: int64

===== Color =====
Color
White            3574
Black             963
Silver            909
Grey              733
Another Color     547
Brown             329
Red               285
Blue              233
Golden            229
Bronze            164
Navy              164
Oily               53
Green              40
Yellow             15
Orange             10
Name: count, dtype: int64

===== Options =====
Options
Full         3235
Standard     2651
Semi Full    2253
NaN           109
Name: count, dtype: int64

===== Engine_Size =====
Engine_Size
NaN    2266
1.6     533
2.0     522
3.5     504
2.5     435
       ...
7.9       1
5.9       1
7.8       1
8.2       1
7.2       1
Name: count, Length: 76, dtype: int64

===== Fuel_Type =====
Fuel_Type
Gas       8051
Diesel     173
Hybrid      24
Name: count, dtype: int64

===== Gear_Type =====
Gear_Type
Automatic    7069
Manual       1105
NaN            74
Name: count, dtype: int64

===== Condition =====
Condition
Used    8248
Name: count, dtype: int64

===== Mileage =====
Mileage
300000    125
200000     96
300        68
100000     67
90000      51
         ...
301515      1
285627      1
199100      1
293715      1
20017       1
Name: count, Length: 2196, dtype: int64

===== Region =====
Region
Riyadh            3312
Dammam            1404
Jeddah            1080
Qassim             316
Al-Medina          304
Makkah             241
Aseer              237
Al-Ahsa            236
Taef               140
Tabouk             135
Jubail             101
Khobar              94
Jazan               92
Abha                87
Hail                86
Hafar Al-Batin      68
Najran              59
Al-Baha             50
Yanbu               39
Al-Jouf             39
Arar                36
Besha               24
Al-Namas            18
Wadi Dawasir        17
Qurayyat            15
Sakaka              12
Sabya                6
Name: count, dtype: int64

===== Price =====
Price
Negotiable    2596
45000          141
55000          127
35000          127
30000          120
              ...
115005           1
120500           1
1846             1
2560             1
1                1
Name: count, Length: 549, dtype: int64

===== Negotiable =====
Negotiable
False    5652
True     2596
Name: count, dtype: int64

### **1.2 Data Information**

Dataset ini berisi informasi mobil bekas yang dijual di Arab Saudi (versi mentah/unclean), terdiri dari **8.248 baris** dan **15 kolom**. Berikut deskripsi masing-masing fitur:

| Kolom | Tipe Data | Deskripsi |
|---|---|---|
| **Link** | String | URL halaman iklan mobil di situs syarah.com. Sebagian nama mobil dalam URL masih berbahasa Arab (belum diterjemahkan). URL dengan pola *`syarah.com/online/...`* menandakan listing mobil bekas yang dijual langsung oleh Syarah, sedangkan URL lainnya merupakan iklan baris yang dipasang oleh pihak ketiga, yaitu dealer maupun penjual perorangan.  |
| **Make** | String | Merek/pabrikan mobil (contoh: Toyota, Nissan, Mercedes).|
| **Type** | String | Model/tipe spesifik dari merek tersebut (contoh: Camry, Patrol, C-Class).|
| **Year** | Integer | Tahun produksi/model mobil. |
| **Origin** | String | Asal mobil: `Saudi`, `Gulf Arabic` (negara Teluk lain), `Other` (luar Teluk).|
| **Color** | String | Warna eksterior mobil (15 kategori, contoh: Black, White, Silver).|
| **Options** | String | Level kelengkapan fitur/trim kendaraan, bersifat **ordinal**: `Standard` < `Semi Full` < `Full`. Terdapat nilai kosong (109 baris). |
| **Engine_Size** | Float | Kapasitas mesin dalam liter (L). Semakin besar nilainya, umumnya tenaga mesin semakin besar namun konsumsi bahan bakar juga meningkat.|
| **Fuel_Type** | String | Jenis bahan bakar: `Gas` (bensin), `Diesel`, atau `Hybrid` (kombinasi mesin bensin + motor listrik, tidak memerlukan pengisian daya eksternal). |
| **Gear_Type** | String | Jenis transmisi: `Automatic` atau `Manual`. |
| **Condition** | String | Kondisi mobil. Hanya berisi **satu nilai unik** (`Used`) di seluruh baris, sehingga tidak memberikan informasi tambahan untuk analisis. |
| **Mileage** | Integer | Jarak tempuh kendaraan dalam **kilometer (km)**.|
| **Region** | String | Wilayah/kota penjualan mobil di Arab Saudi (27 wilayah, contoh: Riyadh, Jeddah, Dammam). |
| **Price** | String | Harga jual mobil dalam Riyal Saudi (SAR). Bertipe **String** (bukan Integer) karena bercampur dengan nilai teks `"Negotiable"` untuk mobil yang harganya bisa dinego. |
| **Negotiable** | Boolean | Menunjukkan apakah harga mobil dapat dinegosiasikan (`True`) atau bersifat tetap/fixed (`False`). Konsisten 100% dengan nilai `"Negotiable"` di kolom Price. |

### **1.3 Statistics Summary**

In [49]:
df.describe(include='all')

,Link,Make,Type,Year,Origin,Color,Options,Engine_Size,Fuel_Type,Gear_Type,Condition,Mileage,Region,Price,Negotiable
count,8248,8248,8248,8248.000000,8153,8248,8139,5982.000000,8248,8174,8248,8.248000e+03,8248,8248,8248
unique,8228,65,435,NaN,3,15,3,NaN,3,2,1,NaN,27,549,2
top,https://syarah.com/%D8%AA%D9%88%D9%8A%D9%88%D8...,Toyota,Land Cruiser,NaN,Saudi,White,Full,NaN,Gas,Automatic,Used,NaN,Riyadh,Negotiable,False
freq,2,2074,374,NaN,6084,3574,3235,NaN,8051,7069,8248,NaN,3312,2596,5652
mean,NaN,NaN,NaN,2014.014064,NaN,NaN,NaN,3.175794,NaN,NaN,NaN,1.494128e+05,NaN,NaN,NaN
std,NaN,NaN,NaN,5.935349,NaN,NaN,NaN,1.567480,NaN,NaN,NaN,3.455258e+05,NaN,NaN,NaN
min,NaN,NaN,NaN,1936.000000,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,1.000000e+02,NaN,NaN,NaN
25%,NaN,NaN,NaN,2012.000000,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,3.700000e+04,NaN,NaN,NaN
50%,NaN,NaN,NaN,2016.000000,NaN,NaN,NaN,2.700000,NaN,NaN,NaN,1.016575e+05,NaN,NaN,NaN
75%,NaN,NaN,NaN,2018.000000,NaN,NaN,NaN,4.000000,NaN,NaN,NaN,1.955520e+05,NaN,NaN,NaN
max,NaN,NaN,NaN,2022.000000,NaN,NaN,NaN,9.000000,NaN,NaN,NaN,2.000000e+07,NaN,NaN,NaN

## **Section 2. Data Cleaning**

### **2.1 Remove Irrelevant Columns**

In [50]:
# Identifikasi jalur penjualan dari pola URL
channel = pd.Series(
    np.where(df['Link'].str.contains('/online/'), 'Penjualan Langsung', 'Iklan Baris'),
    name='Channel'
)

assert len(channel) == len(df)
assert channel.notna().all()

pd.crosstab(channel, df['Negotiable'], margins=True, margins_name='Total')

Negotiable          False  True  Total
Channel
Iklan Baris          5204  2596   7800
Penjualan Langsung    448     0    448
Total                5652  2596   8248

Sebelum kolom `Link` dihapus, pola URL dimanfaatkan untuk mengidentifikasi jalur penjualan setiap listing. Listing dengan URL *`syarah.com/online/...`* merupakan mobil bekas yang dijual langsung oleh Syarah, sedangkan sisanya merupakan iklan baris yang dipasang oleh pihak ketiga, yaitu dealer maupun penjual perorangan. Dari 8.248 listing, sebanyak **7.800 listing (94,6%)** berasal dari iklan baris dan **448 listing (5,4%)** berasal dari penjualan langsung oleh Syarah.

Seluruh **2.596 listing Negotiable** berasal dari iklan baris, atau sekitar 33% dari total iklan baris. Sebaliknya, tidak ada satu pun listing penjualan langsung Syarah yang berstatus Negotiable, karena harganya selalu ditetapkan oleh Syarah. Temuan ini menegaskan bahwa listing Negotiable merupakan mobil milik pihak ketiga yang belum memiliki harga, sehingga relevan sebagai kandidat sumber stok bagi Syarah.

Informasi jalur penjualan ini tidak digunakan sebagai fitur model, karena seluruh listing Negotiable yang menjadi sasaran prediksi berasal dari jalur yang sama, yaitu iklan baris.

In [51]:
df.drop(["Link", "Condition"], axis=1, inplace=True)
df.head()

,Make,Type,Year,Origin,Color,Options,Engine_Size,Fuel_Type,Gear_Type,Mileage,Region,Price,Negotiable
0,Chrysler,C300,2018,Saudi,Black,Full,5.7,Gas,Automatic,103000,Riyadh,114000,False
1,Nissan,Patrol,2016,Saudi,White,Full,4.8,Gas,Automatic,5448,Riyadh,Negotiable,True
2,Nissan,Sunny,2019,Saudi,Silver,Standard,1.5,Gas,Automatic,72418,Riyadh,27500,False
3,Hyundai,Elantra,2019,Saudi,Grey,Standard,1.6,Gas,Automatic,114154,Riyadh,43000,False
4,Hyundai,Elantra,2019,Saudi,Silver,Semi Full,2.0,Gas,Automatic,41912,Riyadh,59500,False

Kolom `Link` dan `Condition` dihapus karena tidak memberikan informasi yang relevan untuk memprediksi harga

- **`Link`**: berisi URL halaman iklan di syarah.com. Selain informasi jalur penjualan yang sudah diambil di atas, URL ini hanya berfungsi sebagai penanda unik tiap listing dan bukan atribut kendaraan, sehingga tidak digunakan sebagai fitur.
- **`Condition`**: hanya punya satu nilai unik (`Used`) di seluruh baris. Karena tidak ada variasi, kolom ini tidak bisa membedakan satu mobil dengan mobil lainnya.

### **2.2 Duplicated Values**

In [52]:
# Cek duplikat
n_dup = df.duplicated().sum()
print(f"Jumlah baris duplikat: {n_dup}")

# Contoh baris duplikat
df[df.duplicated(keep=False)].sort_values(['Make', 'Type', 'Year', 'Mileage']).head(10)

Jumlah baris duplikat: 69

,Make,Type,Year,Origin,Color,Options,Engine_Size,Fuel_Type,Gear_Type,Mileage,Region,Price,Negotiable
5019,BMW,X,2015,Saudi,White,Full,2.0,Gas,Automatic,92000,Jeddah,72000,False
5020,BMW,X,2015,Saudi,White,Full,2.0,Gas,Automatic,92000,Jeddah,72000,False
6431,Cadillac,CT4,2020,Saudi,Grey,Semi Full,NaN,Gas,Automatic,5800,Jeddah,155000,False
6432,Cadillac,CT4,2020,Saudi,Grey,Semi Full,NaN,Gas,Automatic,5800,Jeddah,155000,False
3595,Chevrolet,Blazer,2005,Other,Blue,Full,2.0,Gas,Automatic,213000,Abha,13500,False
3596,Chevrolet,Blazer,2005,Other,Blue,Full,2.0,Gas,Automatic,213000,Abha,13500,False
2085,Chevrolet,Camaro,2017,Other,Silver,Full,3.6,Gas,Automatic,99000,Dammam,109000,False
2604,Chevrolet,Camaro,2017,Other,Silver,Full,3.6,Gas,Automatic,99000,Dammam,109000,False
685,Chevrolet,Caprice,2013,Saudi,Silver,Standard,6.2,Gas,Automatic,55769,Riyadh,90000,False
690,Chevrolet,Caprice,2013,Saudi,Silver,Standard,6.2,Gas,Automatic,55769,Riyadh,90000,False

In [53]:
# Hapus duplikat
before = df.shape[0]
df = df.drop_duplicates(keep='first').reset_index(drop=True)

print(f"{before} -> {df.shape[0]} baris ({n_dup} duplikat dihapus)")

8248 -> 8179 baris (69 duplikat dihapus)

Ditemukan **69 baris duplikat** (atribut identik di semua kolom) yang dihapus dengan mempertahankan kemunculan pertama, karena:

- **Mencegah data leakage**: jika dibiarkan, mobil yang sama bisa masuk ke data train dan test sekaligus, sehingga hasil evaluasi model menjadi terlalu optimis.
- **Menghindari bobot ganda**: satu mobil tidak seharusnya dihitung lebih dari sekali saat training.

### **2.3 Data Consistency Check**

#### **2.3.1 Column Price**

In [54]:
print('Price == "Negotiable":', (df['Price'] == 'Negotiable').sum())
print('Negotiable == True   :', (df['Negotiable'] == True).sum())

Price == "Negotiable": 2585
Negotiable == True   : 2585

In [55]:
# Ubah "Negotiable" menjadi NaN (harga belum tersedia)
n_negotiable = (df['Price'] == 'Negotiable').sum()
df['Price'] = pd.to_numeric(df['Price'].replace('Negotiable', np.nan), errors='raise')

# Validasi: jumlah NaN harus sama dengan jumlah listing Negotiable
assert df['Price'].isna().sum() == n_negotiable
assert df['Price'].isna().sum() == df['Negotiable'].sum()

# Negotiable sudah terwakili oleh NaN di Price -> drop
df = df.drop(columns='Negotiable')

print(f"Price NaN (Negotiable): {df['Price'].isna().sum()} dari {len(df)} baris")

Price NaN (Negotiable): 2585 dari 8179 baris

Kolom `Price` berisi nilai teks `"Negotiable"` sebanyak **2.585 baris**, dan jumlah ini sama persis dengan baris `Negotiable == True`. Artinya kedua kolom ini merepresentasikan informasi yang sama.

Baris **Negotiable tetap dipertahankan sementara**, baris-baris ini tetap mengikuti seluruh proses cleaning agar kualitas datanya setara dengan listing berharga. Di akhir notebook, baris dengan `Price` NaN dipisahkan sebagai `df_negotiable`, yang akan digunakan sebagai data inference untuk memberikan estimasi harga pasar setelah model selesai dibangun.

Catatan: selama proses cleaning, `Price` bertipe `float64` karena tipe integer tidak dapat menyimpan NaN. Konversi ke integer dilakukan di akhir notebook setelah baris NaN dipisahkan.

#### **2.3.2 Column Type**

Kolom `Type` berisi nama model kendaraan. Dataset ini merupakan hasil terjemahan dari versi bahasa Arab, sehingga sebagian nama model berpotensi keliru akibat proses konversi dari huruf Arab ke huruf Latin. Untuk memeriksanya, setiap nilai `Type` yang mencurigakan dicocokkan dengan nilai aslinya pada dataset versi bahasa Arab (`UsedCarsSA_Unclean_Ar.xlsx`), yang memiliki urutan baris yang sama dengan dataset versi Inggris.

In [56]:
print(f"Jumlah Type unik: {df['Type'].nunique()}\n")

for make, types in df.groupby('Make')['Type'].unique().items():
    print(f"{make}: {sorted(types)}")

Jumlah Type unik: 435

Ashok: ['Leyland']
Aston Martin: ['DB9', 'Vanquish', 'Vantage']
Audi: ['A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'Q5', 'Q7', 'S5', 'S8']
BMW: ['The 1', 'The 3', 'The 4', 'The 5', 'The 6', 'The 7', 'The M', 'X', 'Z']
BYD: ['F3', 'S6', 'S7']
Bentley: ['Arnage', 'Bentayga', 'Continental GT', 'Flying Spur']
Buick: ['Riviera']
Cadillac: ['ATS', 'CT-S', 'CT4', 'CT5', 'CT6', 'DTS', 'Eldorado', 'Escalade', 'Fleetwood', 'Other', 'SRX', 'STS', 'XT5']
Changan: ['CS35', 'CS35 Plus', 'CS75', 'CS85', 'CS95', 'Eado', 'Seven', 'V7']
Chery: ['QQ', 'Tiggo']
Chevrolet: ['Abeka', 'Avalanche', 'Aveo', 'Blazer', 'Camaro', 'Caprice', 'Caprice Classic', 'Colorado', 'Corvette', 'Cruze', 'Impala', 'Kaptiva', 'Lumina', 'Malibu', 'Optra', 'Other', 'Pick up', 'Silverado', 'Spark', 'Suburban', 'Tahoe', 'Trailblazer', 'Traverse', 'Van Express']
Chrysler: ['300', 'C200', 'C300', 'Grand Voyager', 'M300', 'New Yorker', 'S300', 'SRT', 'Town and Country']
Classic: ['Cadillac', 'Jaguar', 'Mini Cooper']
Daihatsu: ['Delta', 'Gran Max', 'Terios', 'Terios Ground']
Dodge: ['Challenger', 'Charger', 'Dakota', 'Durango', 'Nitro', 'Ram']
FAW: ['B50', 'T77', 'X40', 'ِACTIS V80']
Ferrari: ['GTB 599 Fiorano']
Fiat: ['500', 'Doblo', 'Fiorino', 'Linea', 'Other']
Ford: ['Bronco', 'E350', 'Echo Sport', 'Edge', 'Expedition', 'Explorer', 'F150', 'Flex', 'Focus', 'Freestar', 'Fusion', 'Marquis', 'Mustang', 'Other', 'Ranger', 'Taurus', 'Thunderbird', 'Transit', 'Van', 'Vego', 'Victoria']
Foton: ['Mini Van', 'Suvana']
GAC: ['GS3', 'GS4', 'GS8']
GMC: ['Acadia', 'Behbehani', 'C5700', 'Envoy', 'Other', 'Safari', 'Savana', 'Sierra', 'Suburban', 'Terrain', 'Yukon']
Geely: ['Azkarra', 'Coolray', 'EC7', 'EC8', 'Emgrand', 'GC7', 'GS', 'Other', 'X7']
Genesis: ['Coupe', 'G330', 'G70', 'G80', 'Other', 'Platinum', 'Prestige', 'Prestige Plus', 'Royal']
Great Wall: ['Power', 'Wingle']
HAVAL: ['H2', 'H6', 'H9']
Honda: ['Accord', 'CRV', 'City', 'Civic', 'Crosstour', 'HRV', 'MR-V', 'Odyssey', 'Other', 'Pilot']
Hummer: ['H-2', 'H3']
Hyundai: ['Accent', 'Avante', 'Azera', 'Bus County', 'Centennial', 'Coupe', 'Coupe S', 'Creta', 'Elantra', 'Genesis', 'H1', 'H100', 'Kona', 'Other', 'Palisade', 'Senta fe', 'Sonata', 'Tucson', 'Tuscani', 'Veloster', 'Veracruz', 'i10', 'i40']
INFINITI: ['FX', 'G', 'M', 'Q', 'QX']
Isuzu: ['D-MAX', 'Dyna', 'Other']
Iveco: ['Daily']
JAC: ['Dyna', 'J5']
Jaguar: ['F Type', 'F-Pace', 'X Type', 'XF', 'XJ', 'XJR']
Jeep: ['Cherokee', 'Commander', 'Compass', 'Grand Cherokee', 'Liberty', 'Patriot', 'Wrangler']
Kia: ['Cadenza', 'Carens', 'Carenz', 'Carnival', 'Cerato', 'Cores', 'K4000G', 'K5', 'Mohave', 'Opirus', 'Optima', 'Pegas', 'Picanto', 'Rio', 'Sedona', 'Seltos', 'Sorento', 'Soul', 'Sportage', 'Stinger']
Land Rover: ['Defender', 'Discovery', 'LR2', 'Other', 'Range Rover']
Lexus: ['ES', 'GS', 'GX', 'IS', 'LS', 'LX', 'NX', 'RC', 'RX', 'UX']
Lifan: ['LF X60']
Lincoln: ['Continental GT', 'MKS', 'MKX', 'MKZ', 'Navigator', 'The LS', 'Town Car']
MAN: ['Big Truck']
MG: ['3', '350', '360', '5', '6', 'GS', 'HS', 'RX5', 'RX8', 'T60', 'ZS']
MINI: ['Copper', 'Countryman']
Maserati: ['Gamble', 'Levante', 'Quattroporte']
Mazda: ['2', '3', '323', '6', 'BT-50', 'CX3', 'CX5', 'CX7', 'CX9']
Mercedes: ['A', 'ALB', 'Actros', 'Atego', 'Axor', 'C', 'CL', 'CLA', 'CLS', 'E', 'G', 'GL', 'GLA', 'GLB', 'GLC', 'GLE', 'GT', 'ML', 'Maybach', 'POS24', 'R', 'S', 'SE', 'SEL', 'SL', 'SLK', 'Sprinter', 'Viano']
Mercury: ['Grand Marquis', 'Marquis', 'Milan', 'Montero1', 'Montero2']
Mitsubishi: ['ASX', 'Attrage', 'Fuso Canter', 'Galant', 'L200', 'L300', 'Lancer', 'Montero', 'Nativa', 'Osa Bus', 'Other', 'Outlander', 'Pajero', 'Space Star']
Nissan: ['Altima', 'Armada', 'Bus Urvan', 'Datsun', 'Gloria', 'Juke', 'KICKS', 'Land Cruiser Pickup', 'Maxima', 'Murano', 'Navara', 'Pathfinder', 'Patrol', 'Sentra', 'Silvia', 'Sunny', 'Sylvian Bus', 'Tiida', 'VTC', 'X-Terra', 'X-Trail', 'Z350', 'Z370']
Other: ['Other']
Peugeot: ['3008', '301', '307', '308', '5008', 'Boxer', 'Partner']
Pontiac: ['Bonneville']
Porsche: ['911', 'Cayenne', 'Cayenne S', 'Cayenne Turbo', 'Cayenne Turbo GTS', 'Cayenne Turbo S', 'Cayman', 'Macan', 'Other', 'Panamera']
Renault: ['Capture', 'Dokker', 'Duster', 'Fluence', 'Koleos', 'Logan', 'Megane', 'Safrane', 'Symbol', 'Talisman', 'Trafic']
Rolls-Royce: ['Camargue', 'Ghost']
SsangYong: ['Koranado', 'Rexton']
Subaru: ['Forester']
Suzuki: ['APV', 'Carry', 'Celerio', "D'max", 'Dzire', 'Ertiga', 'Grand Vitara', 'Jimny', 'Other', 'SX4', 'Super Carry', 'Vitara']
Tata: ['Bus', 'Dyna', 'Nexon']
Toyota: ['4Runner', 'Aurion', 'Avalon', 'Avanza', 'C-HR', 'Camry', 'Ciocca', 'Coaster', 'Corolla', 'Corolla Cross', 'Cressida', 'Crown', 'Dyna', 'Echo', 'FJ', 'Furniture', 'Hiace', 'Hilux', 'Innova', 'Land Cruiser', 'Land Cruiser 70', 'Land Cruiser Pickup', 'Other', 'Prado', 'Previa', 'Prius', 'Rav4', 'Rush', 'Sienna LE', 'Toyota 86', 'Tundra', 'Yaris']
Victory Auto: ['Van R']
Volkswagen: ['Beetle', 'Bora', 'CC', 'Golf', 'Jetta', 'Passat', 'Tiguan', 'Touareg']
Volvo: ['FH', 'XC90']
Zhengzhou: ['Pick up']
Škoda: ['Fabia', 'Superb']

Dari daftar di atas, terdapat sejumlah nilai `Type` yang tidak lazim sebagai nama model kendaraan. Sebagian berupa kata bahasa Inggris yang tidak berkaitan dengan otomotif (misalnya `Furniture` dan `Gamble`), sebagian lagi berupa nama yang mirip dengan model asli namun penulisannya keliru (misalnya `Senta fe` dan `Kaptiva`). Selain itu, terdapat nilai yang mengandung karakter non-Latin dan nilai yang merupakan nama dealer.

In [57]:
suspicious_types = [
    'Furniture', 'Senta fe', 'Ciocca', 'Copper', 'Vego', 'Carenz',
    'POS24', 'Gamble', 'Kaptiva', 'Cores', 'Abeka', 'Montero2',
    'Sylvian Bus', 'Capture', 'Osa Bus', 'Koranado', 'Montero1',
    '\u0650ACTIS V80', 'Behbehani',
]

# Cek tambahan: Type yang mengandung karakter non-Latin
print("Type dengan karakter non-ASCII:", df.loc[~df['Type'].map(str.isascii), 'Type'].unique())

anomali_type = df[df['Type'].isin(suspicious_types)]
print(f"Jumlah baris dengan Type mencurigakan: {len(anomali_type)}")
anomali_type.groupby(['Make', 'Type']).size().sort_values(ascending=False)

Type dengan karakter non-ASCII: ['ِACTIS V80']
Jumlah baris dengan Type mencurigakan: 296

Make        Type
Toyota      Furniture      129
Hyundai     Senta fe        69
Toyota      Ciocca          36
MINI        Copper          12
Ford        Vego             9
Kia         Carenz           6
Mercedes    POS24            5
Maserati    Gamble           4
Chevrolet   Kaptiva          4
            Abeka            4
Kia         Cores            4
Nissan      Sylvian Bus      3
Mercury     Montero2         3
Mitsubishi  Osa Bus          2
Renault     Capture          2
FAW         ِACTIS V80       1
GMC         Behbehani        1
Mercury     Montero1         1
SsangYong   Koranado         1
dtype: int64

In [58]:
# Dataset mentah versi Inggris dan Arab memiliki urutan baris yang sama
df_raw_en = pd.read_csv('../data/raw/UsedCarsSA_Unclean_EN.csv')
df_raw_ar = pd.read_excel('../data/raw/UsedCarsSA_Unclean_Ar.xlsx')

assert len(df_raw_en) == len(df_raw_ar)
assert (df_raw_en['Year'].values == df_raw_ar['Year'].values).all()

validasi = pd.DataFrame({
    'Make': df_raw_en['Make'],
    'Type_EN': df_raw_en['Type'],
    'Type_AR': df_raw_ar['Type'],
})
validasi = validasi[validasi['Type_EN'].isin(suspicious_types)].drop_duplicates()
validasi.sort_values('Make').reset_index(drop=True)

          Make      Type_EN      Type_AR
0    Chevrolet      Kaptiva      كابتيفا
1    Chevrolet        Abeka        ابيكا
2          FAW   ِACTIS V80   ِACTIS V80
3         Ford         Vego         فيجو
4          GMC    Behbehani      بهبهاني
5      Hyundai     Senta fe       سنتافي
6          Kia       Carenz       كارينز
7          Kia        Cores        كوريس
8         MINI       Copper         كوبر
9     Maserati       Gamble        جيبلي
10    Mercedes        POS24       بوز 24
11     Mercury     Montero1      مونتيغو
12     Mercury     Montero2    ماونتينير
13  Mitsubishi      Osa Bus     باص روزا
14      Nissan  Sylvian Bus  باص سيلفيان
15     Renault      Capture       كابتشر
16   SsangYong     Koranado      كوراندو
17      Toyota    Furniture      فورتشنر
18      Toyota       Ciocca       سيكويا

In [59]:
# Mapping Type yang keliru ke nama model yang benar
# Divalidasi dengan dataset versi Arab dan halaman kategori syarah.com
type_mapping = {
    # Kesalahan konversi nama Arab ke Inggris
    'Furniture': 'Fortuner',         # فورتشنر - Toyota
    'Senta fe': 'Santa Fe',          # سنتافي - Hyundai
    'Ciocca': 'Sequoia',             # سيكويا - Toyota
    'Copper': 'Cooper',              # كوبر - MINI
    'Vego': 'Figo',                  # فيجو - Ford
    'Carenz': 'Carens',              # كارينز - Kia
    'POS24': 'Short Bonnet',         # بوز 24 - Mercedes truk klasik (1959-1995)
    'Gamble': 'Ghibli',              # جيبلي - Maserati
    'Kaptiva': 'Captiva',            # كابتيفا - Chevrolet
    'Cores': 'Quoris',               # كوريس - Kia
    'Abeka': 'Epica',                # ابيكا - Chevrolet
    'Montero2': 'Mountaineer',       # ماونتينير - Mercury
    'Sylvian Bus': 'Civilian',       # باص سيلفيان - Nissan
    'Capture': 'Captur',             # كابتشر - Renault
    'Osa Bus': 'Rosa',               # باص روزا - Mitsubishi
    'Koranado': 'Korando',           # كوراندو - SsangYong
    'Montero1': 'Montego',           # مونتيغو - Mercury

    # Karakter Arab tersembunyi (kasrah, U+0650) di depan nama
    '\u0650ACTIS V80': 'ACTIS V80',  # FAW
}

# Nilai yang bukan nama model -> di-drop
drop_types = ['Behbehani']           # بهبهاني - nama dealer

# Pastikan semua Type mencurigakan sudah punya penanganan
assert set(type_mapping) | set(drop_types) == set(suspicious_types)

# Perbaikan
before = len(df)
df = df[~df['Type'].isin(drop_types)].reset_index(drop=True)
df['Type'] = df['Type'].replace(type_mapping)

# Validasi
assert not df['Type'].isin(suspicious_types).any(), "Masih ada Type mencurigakan"
assert df['Type'].map(str.isascii).all(), "Masih ada karakter non-ASCII di Type"
print(f"{before} -> {len(df)} baris")

8179 -> 8178 baris

Ditemukan **296 baris** dengan nilai `Type` yang tidak sesuai dengan nama model mobil yang sebenarnya. Hampir seluruhnya berasal dari kesalahan konversi nama model dari huruf Arab ke huruf Latin. Kesalahan ini terjadi karena huruf Arab tidak membedakan beberapa bunyi, misalnya ب dapat terbaca sebagai B atau P, dan ف sebagai F atau V, sehingga nama yang dihasilkan meleset dari nama aslinya (contoh: `Vego` untuk Ford Figo). Pada kasus yang lebih parah, nama model justru diterjemahkan menjadi kata bahasa Inggris lain yang bunyinya mirip, seperti `Furniture` untuk Toyota Fortuner.

Setiap nilai divalidasi dengan mencocokkannya ke nilai aslinya pada dataset versi bahasa Arab, lalu diperbaiki ke nama model yang benar:

| Make | Type (asli) | Type (Arab) | Type (perbaikan) | Jumlah Baris |
|---|---|---|---|---|
| Toyota | Furniture | فورتشنر | Fortuner | 129 |
| Hyundai | Senta fe | سنتافي | Santa Fe | 69 |
| Toyota | Ciocca | سيكويا | Sequoia | 36 |
| MINI | Copper | كوبر | Cooper | 12 |
| Ford | Vego | فيجو | Figo | 9 |
| Kia | Carenz | كارينز | Carens | 6 |
| Mercedes | POS24 | بوز 24 | Short Bonnet | 5 |
| Maserati | Gamble | جيبلي | Ghibli | 4 |
| Chevrolet | Kaptiva | كابتيفا | Captiva | 4 |
| Kia | Cores | كوريس | Quoris | 4 |
| Chevrolet | Abeka | ابيكا | Epica | 4 |
| Mercury | Montero2 | ماونتينير | Mountaineer | 3 |
| Nissan | Sylvian Bus | باص سيلفيان | Civilian | 3 |
| Renault | Capture | كابتشر | Captur | 2 |
| Mitsubishi | Osa Bus | باص روزا | Rosa | 2 |
| SsangYong | Koranado | كوراندو | Korando | 1 |
| Mercury | Montero1 | مونتيغو | Montego | 1 |
| FAW | ACTIS V80 | ACTIS V80 | ACTIS V80 | 1 |
| GMC | Behbehani | بهبهاني | *(di-drop)* | 1 |

Baris-baris ini tetap dipertahankan karena atribut lainnya valid, hanya nama modelnya yang keliru. Perbaikan ini penting agar listing dengan model yang sama tidak terpecah menjadi dua kategori berbeda, misalnya `Carenz` (6 baris) dan `Carens` (1 baris) yang sebenarnya merupakan model yang sama dan kini digabung menjadi satu kategori.

Terdapat dua kasus khusus. Pertama, nilai `ACTIS V80` pada merek FAW secara tampilan sudah benar, namun mengandung karakter Arab tersembunyi (harakat kasrah) di bagian depannya, sehingga terbaca sebagai nilai yang berbeda. Karakter ini sudah ada sejak data sumber dan dihapus agar nilainya seragam. Kedua, nilai `Behbehani` merupakan nama dealer, bukan nama model mobil. Karena model aslinya tidak dapat ditentukan, baris ini dihapus (hanya 1 baris sehingga tidak berdampak signifikan pada data). Jumlah data setelah penghapusan: 8.179 → **8.178 baris**.

#### **2.3.3 Column Make**

In [60]:
print(f"Jumlah Make unik: {df['Make'].nunique()}")
print(sorted(df['Make'].unique()))

Jumlah Make unik: 65
['Ashok', 'Aston Martin', 'Audi', 'BMW', 'BYD', 'Bentley', 'Buick', 'Cadillac', 'Changan', 'Chery', 'Chevrolet', 'Chrysler', 'Classic', 'Daihatsu', 'Dodge', 'FAW', 'Ferrari', 'Fiat', 'Ford', 'Foton', 'GAC', 'GMC', 'Geely', 'Genesis', 'Great Wall', 'HAVAL', 'Honda', 'Hummer', 'Hyundai', 'INFINITI', 'Isuzu', 'Iveco', 'JAC', 'Jaguar', 'Jeep', 'Kia', 'Land Rover', 'Lexus', 'Lifan', 'Lincoln', 'MAN', 'MG', 'MINI', 'Maserati', 'Mazda', 'Mercedes', 'Mercury', 'Mitsubishi', 'Nissan', 'Other', 'Peugeot', 'Pontiac', 'Porsche', 'Renault', 'Rolls-Royce', 'SsangYong', 'Subaru', 'Suzuki', 'Tata', 'Toyota', 'Victory Auto', 'Volkswagen', 'Volvo', 'Zhengzhou', 'Škoda']

Dari 65 nilai unik pada kolom `Make`, seluruhnya merupakan nama merek kendaraan yang valid kecuali dua nilai, yaitu `Other` dan `Classic`. Kedua nilai ini bukan nama merek, sehingga perlu diperiksa lebih lanjut untuk menentukan penanganannya.

In [61]:
anomali_make = df[df['Make'] == 'Other']
print(f"Jumlah baris dengan Make 'Other': {len(anomali_make)}")
anomali_make

Jumlah baris dengan Make 'Other': 15

,Make,Type,Year,Origin,Color,Options,Engine_Size,Fuel_Type,Gear_Type,Mileage,Region,Price
2818,Other,Other,2012,Other,Blue,Full,2.4,Gas,Automatic,150,Jazan,NaN
2970,Other,Other,2009,Saudi,Black,Full,NaN,Gas,Automatic,218000,Riyadh,NaN
3044,Other,Other,2019,Other,White,Full,8.0,Diesel,Manual,24643,Qassim,330000.0
4751,Other,Other,2009,Other,Orange,Standard,NaN,Diesel,Manual,1300,Al-Medina,26000.0
5062,Other,Other,2007,Saudi,Red,Standard,3.5,Gas,Manual,125,Qassim,7000.0
5077,Other,Other,1992,Saudi,White,Semi Full,2.2,Gas,Manual,120000,Jeddah,NaN
5379,Other,Other,2011,Other,White,Standard,NaN,Diesel,Manual,100000,Jazan,NaN
5472,Other,Other,2019,Saudi,Brown,Full,1.0,Gas,Manual,4000,Jeddah,39000.0
5529,Other,Other,2006,Saudi,Oily,Standard,6.5,Diesel,Manual,81250,Riyadh,NaN
5653,Other,Other,2021,Other,Yellow,Semi Full,1.2,Gas,Manual,3000,Jeddah,5500.0
5872,Other,Other,2004,Saudi,White,Full,NaN,Diesel,Automatic,6000,Taef,NaN
6800,Other,Other,2020,Other,Black,Standard,1.1,Gas,Manual,2848,Al-Baha,2000.0
7151,Other,Other,2019,Other,White,Semi Full,NaN,Gas,Manual,1000,Khobar,NaN
7743,Other,Other,2011,Other,Black,Full,1.8,Gas,Manual,33000,Al-Medina,50000.0
7816,Other,Other,1980,Other,Yellow,Standard,NaN,Diesel,Manual,2500,Qassim,220000.0

In [62]:
df = df[df['Make'] != 'Other'].reset_index(drop=True)

Ditemukan **15 baris** dengan nilai `Make == 'Other'`, dan seluruhnya juga memiliki `Type == 'Other'`. Artinya, listing ini tidak memiliki informasi merek maupun model kendaraan sama sekali, padahal kedua atribut tersebut merupakan faktor utama yang menentukan harga mobil bekas. Tanpa informasi ini, mobil dengan segmen yang sangat berbeda (misalnya mobil ekonomis dan mobil mewah) akan dikelompokkan ke dalam satu kategori yang sama, sehingga berpotensi menjadi noise bagi model. Selain itu, nilai merek dan model aslinya tidak dapat ditelusuri dari atribut lain, sehingga perbaikan seperti pada kolom `Type` sebelumnya tidak dapat dilakukan.

Karena jumlahnya sangat kecil (sekitar 0,18% dari data), baris-baris ini dihapus tanpa berdampak signifikan terhadap ukuran dataset. Jumlah data setelah penghapusan: 8.178 → **8.163 baris**.

In [63]:
df[df["Make"]=="Classic"]

,Make,Type,Year,Origin,Color,Options,Engine_Size,Fuel_Type,Gear_Type,Mileage,Region,Price
2666,Classic,Cadillac,1995,Saudi,Red,Full,8.0,Gas,Automatic,119,Riyadh,25000.0
2812,Classic,Jaguar,1936,Other,Bronze,Full,NaN,Gas,Automatic,4750,Tabouk,NaN
5441,Classic,Mini Cooper,1972,Other,Another Color,Full,1.3,Gas,Manual,1000,Dammam,42000.0

In [64]:
df = df[df['Make'] != 'Classic'].reset_index(drop=True)

Selain `Other`, ditemukan juga **3 baris** dengan nilai `Make == 'Classic'`. Nilai ini bukan nama merek, melainkan kategori khusus di Syarah untuk mobil klasik, terlihat dari kolom `Type` yang justru berisi nama merek (Jaguar, Cadillac) atau gabungan merek dan model (Mini Cooper). Ketiga mobil ini diproduksi antara tahun 1936 hingga 1995, dan harga mobil klasik umumnya tidak mengikuti pola depresiasi seperti mobil bekas pada umumnya, bahkan bisa meningkat seiring usia karena nilai koleksinya.

Karena karakteristik harganya berbeda dari mayoritas data dan jumlahnya terlalu sedikit untuk dipelajari polanya oleh model (hanya 2 baris yang memiliki harga), baris-baris ini dihapus. Jumlah data setelah penghapusan: 8.163 → **8.160 baris**.

#### **2.3.4 Column Color**

In [65]:
print(f"Jumlah Color unik: {df['Color'].nunique()}")
print(sorted(df['Color'].unique()))

Jumlah Color unik: 15
['Another Color', 'Black', 'Blue', 'Bronze', 'Brown', 'Golden', 'Green', 'Grey', 'Navy', 'Oily', 'Orange', 'Red', 'Silver', 'White', 'Yellow']

In [66]:
df['Color'] = df['Color'].replace({'Oily': 'Olive'})
df['Color'].value_counts()

Color
White            3537
Black             951
Silver            904
Grey              724
Another Color     543
Brown             327
Red               280
Golden            228
Blue              228
Navy              164
Bronze            162
Olive              51
Green              39
Yellow             13
Orange              9
Name: count, dtype: int64

Kolom `Color` berisi 15 nilai unik tanpa nilai kosong maupun variasi penulisan. Namun, terdapat nilai `Oily` sebanyak **51 baris** yang bukan merupakan nama warna dalam bahasa Inggris. Setelah dicocokkan dengan dataset versi bahasa Arab, nilai ini berasal dari kata **زيتي** (*zaiti*), yang dalam konteks warna berarti hijau zaitun. Kata tersebut diterjemahkan secara harfiah menjadi "Oily", sehingga nilainya diganti menjadi `Olive` agar lebih mudah dipahami.

Nilai `Another Color` (543 baris) tetap dipertahankan sebagai kategori tersendiri karena warna aslinya tidak dapat ditelusuri, dan jumlahnya cukup besar untuk dijadikan satu kelompok.

#### **2.3.5 Column Engine_Size**

In [67]:
models = ['Camry', 'Corolla', 'Accent', 'Land Cruiser', 'Yukon', 'Tahoe']

(df[df['Type'].isin(models)]
   .groupby(['Make', 'Type'])['Engine_Size']
   .agg(['count', 'min', 'median', 'max']))

                        count  min  median  max
Make      Type
Chevrolet Tahoe           136  1.0     5.3  8.5
GMC       Yukon           144  1.0     5.3  9.0
Hyundai   Accent          220  1.2     1.4  2.5
Toyota    Camry           218  1.0     2.5  9.0
          Corolla         152  1.0     1.6  8.1
          Land Cruiser    237  1.0     4.6  9.0

In [68]:
df.loc[df['Type'] == 'Camry', 'Engine_Size'].value_counts().sort_index()

Engine_Size
1.0      4
1.1      3
1.3      1
1.4      5
1.5      3
1.6      5
1.7      1
1.8      3
2.0      7
2.2      2
2.4     39
2.5    121
2.6      1
2.7      1
3.0      1
3.1      1
3.5     11
3.6      1
4.0      5
7.8      1
9.0      2
Name: count, dtype: int64

Secara keseluruhan, kolom `Engine_Size` memiliki rentang nilai 1,0–9,0 L yang masih wajar untuk kendaraan. Namun, jika dilihat per model, terdapat nilai yang tidak konsisten dengan spesifikasi model tersebut. Sedan kecil seperti Toyota Corolla, yang umumnya bermesin sekitar 1,6 L, memiliki nilai maksimum hingga 8,1 L. Sebaliknya, SUV besar seperti Land Cruiser, Yukon, dan Tahoe, yang umumnya bermesin di atas 4,5 L, memiliki nilai minimum 1,0 L. Pada Toyota Camry, mayoritas listing bermesin 2,4–2,5 L, tetapi terdapat juga listing dengan kapasitas 1,0 L, 7,8 L, dan 9,0 L. Nilai-nilai ekstrem ini kemungkinan berasal dari kesalahan input oleh penjual, misalnya memilih nilai terendah atau tertinggi pada form secara asal.

Karena satu model dapat memiliki beberapa varian mesin yang sah (misalnya Camry tersedia dalam versi 2,5 L dan 3,5 L), koreksi memerlukan pencocokan manual dengan spesifikasi asli tiap model. Hal ini tidak dilakukan karena keterbatasan waktu, sehingga dicatat sebagai keterbatasan data.

#### **2.3.6 Other Columns**

In [69]:
for col in ['Origin', 'Options', 'Fuel_Type', 'Gear_Type', 'Region']:
    print(f"{col} ({df[col].nunique()} nilai unik): {sorted(df[col].dropna().unique())}")

Origin (3 nilai unik): ['Gulf Arabic', 'Other', 'Saudi']
Options (3 nilai unik): ['Full', 'Semi Full', 'Standard']
Fuel_Type (3 nilai unik): ['Diesel', 'Gas', 'Hybrid']
Gear_Type (2 nilai unik): ['Automatic', 'Manual']
Region (27 nilai unik): ['Abha', 'Al-Ahsa', 'Al-Baha', 'Al-Jouf', 'Al-Medina', 'Al-Namas', 'Arar', 'Aseer', 'Besha', 'Dammam', 'Hafar Al-Batin', 'Hail', 'Jazan', 'Jeddah', 'Jubail', 'Khobar', 'Makkah', 'Najran', 'Qassim', 'Qurayyat', 'Riyadh', 'Sabya', 'Sakaka', 'Tabouk', 'Taef', 'Wadi Dawasir', 'Yanbu']

In [70]:
print(f"Rentang Year: {df['Year'].min()} - {df['Year'].max()}")
df['Year'].value_counts().sort_index().tail()

Rentang Year: 1961 - 2022

Year
2018    768
2019    631
2020    558
2021    190
2022      2
Name: count, dtype: int64

Kolom `Origin`, `Options`, `Fuel_Type`, `Gear_Type`, dan `Region` sudah konsisten, tanpa salah tulis maupun variasi penulisan. Nilai kosong pada kolom `Origin`, `Options`, dan `Gear_Type` akan ditangani pada bagian Missing Values.

Kolom `Year` memiliki rentang 1961–2022. Terdapat 2 listing dengan tahun 2022, yang masih wajar karena data dikumpulkan pada tahun 2021 dan produsen mobil umumnya sudah merilis model tahun berikutnya sebelum tahun tersebut dimulai.

### **2.4 Identify Missing Values**

In [71]:
missing = df.drop(columns='Price').isna().sum()
missing = missing[missing > 0].sort_values(ascending=False)

pd.DataFrame({
    'Jumlah': missing,
    'Persentase (%)': (missing / len(df) * 100).round(2),
})

             Jumlah  Persentase (%)
Engine_Size    2247           27.54
Options         109            1.34
Origin           95            1.16
Gear_Type        74            0.91

Terdapat empat kolom fitur yang memiliki nilai kosong. Kolom `Engine_Size` memiliki jumlah terbanyak, yaitu **2.247 baris (27,54%)**, sedangkan `Options`, `Origin`, dan `Gear_Type` masing-masing hanya sekitar 1% dari data. Kolom `Price` tidak dimasukkan karena nilai kosongnya merupakan listing Negotiable yang akan dipisahkan sebagai data inference, bukan diimputasi.

Baris dengan nilai kosong tidak dihapus karena akan menghilangkan data dalam jumlah besar. Jika seluruh baris yang memiliki nilai kosong dihapus, sebanyak **1.216 dari 5.583 listing berharga (21,8%)** akan hilang dari data training, padahal atribut lain pada baris-baris tersebut masih valid dan informatif. Selain itu, listing Negotiable yang memiliki nilai kosong juga tidak akan bisa diprediksi harganya, karena model tidak dapat menerima input dengan nilai kosong.

Oleh karena itu, nilai kosong akan diisi melalui imputasi pada tahap modeling setelah train-test split dan dimasukkan ke dalam pipeline. Imputasi memerlukan statistik dari data (misalnya median untuk kolom numerik dan modus untuk kolom kategorikal), sehingga statistik tersebut hanya dihitung dari data train agar tidak terjadi data leakage. Dengan pipeline, proses imputasi yang sama juga akan diterapkan secara otomatis pada data baru yang akan diprediksi.

### **2.5 Identify Anomaly Values**

#### **2.5.1 Column Price**

Kolom `Price` merupakan target yang akan diprediksi, sehingga nilai yang tidak wajar perlu diperiksa karena dapat membuat model mempelajari pola harga yang keliru. Pemeriksaan pertama difokuskan pada listing dengan harga sangat rendah, dengan membandingkan listing di bawah 5.000 SAR dan listing pada rentang 5.000–10.000 SAR.

In [72]:
priced = df[df['Price'].notna()]

print(priced['Price'].describe().round(0))
print()
print(f"Price < 5,000          : {(priced['Price'] < 5_000).sum()} listing")
print(f"5,000 <= Price < 10,000: {priced['Price'].between(5_000, 10_000, inclusive='left').sum()} listing")

count       5583.0
mean       78469.0
std        76247.0
min            0.0
25%        35000.0
50%        58000.0
75%        95000.0
max      1150000.0
Name: Price, dtype: float64

Price < 5,000          : 96 listing
5,000 <= Price < 10,000: 58 listing

Harga minimum pada data adalah 0 SAR, padahal kuartil bawah (25%) sudah berada di 35.000 SAR. Terdapat **96 listing** dengan harga di bawah 5.000 SAR dan 58 listing pada rentang 5.000–10.000 SAR. 

Untuk mengetahui apakah harga-harga rendah ini wajar, listing di bawah 5.000 SAR dibandingkan dengan harga normal dari model dan tahun yang sama.

In [73]:
low = priced[priced['Price'] < 5_000]

# Median dan jumlah listing normal (>= 5.000) untuk Make, Type, dan Year yang sama
normal_ref = (priced[priced['Price'] >= 5_000]
              .groupby(['Make', 'Type', 'Year'])['Price']
              .agg(Median_Normal='median', N_Normal='size'))

compare = low.merge(normal_ref, left_on=['Make', 'Type', 'Year'], right_index=True, how='left')
compare['Ratio'] = (compare['Price'] / compare['Median_Normal']).round(3)

# Hanya gunakan pembanding dengan minimal 3 listing agar median lebih stabil
reliable = compare[compare['N_Normal'] >= 3]
print(f"Listing dengan pembanding >= 3: {len(reliable)} dari {len(low)}")
print(f"Median rasio harga terhadap harga normal: {reliable['Ratio'].median():.1%}")

(reliable[['Make', 'Type', 'Year', 'Mileage', 'Price', 'Median_Normal', 'N_Normal', 'Ratio']]
    .sort_values('Price')
    .head(15))

Listing dengan pembanding >= 3: 54 dari 96
Median rasio harga terhadap harga normal: 2.3%

         Make     Type  Year  Mileage   Price  Median_Normal  N_Normal  Ratio
7099  Genesis      G80  2018   170000   500.0        98000.0       7.0  0.005
7743   Toyota    Yaris  2018   100000   850.0        35000.0      16.0  0.024
3701      Kia      Rio  2019    55500   884.0        35750.0      10.0  0.025
7341   Toyota    Yaris  2019    85000   950.0        38250.0      16.0  0.025
1695       MG        5  2020    41000   988.0        41000.0       4.0  0.024
7783  Hyundai  Elantra  2019    89000   993.0        50250.0      36.0  0.020
4342   Toyota  Corolla  2020    48563  1002.0        62000.0      10.0  0.016
3636  Hyundai   Sonata  2020     7000  1010.0        85000.0      11.0  0.012
2173  Hyundai  Elantra  2020    27000  1010.0        57500.0      15.0  0.018
6933   Toyota  Corolla  2020    14000  1013.0        62000.0      10.0  0.016
7800   Toyota    Yaris  2018   169000  1046.0        35000.0      16.0  0.030
2705  Hyundai   Accent  2020    35000  1066.0        43000.0      10.0  0.025
8081   Toyota  Corolla  2020    26000  1086.0        62000.0      10.0  0.018
6277  Renault   Duster  2017   106000  1128.0        26500.0       4.0  0.043
5422  Hyundai     Kona  2020     6400  1156.0        68500.0       4.0  0.017

In [74]:
print(f"Median tahun listing < 5.000 SAR: {low['Year'].median():.0f}")
print(f"Listing tahun 2018 ke atas: {(low['Year'] >= 2018).sum()} dari {len(low)}")

Median tahun listing < 5.000 SAR: 2019
Listing tahun 2018 ke atas: 77 dari 96

Listing dengan harga di bawah 5.000 SAR didominasi oleh mobil keluaran baru, dengan median tahun 2019 dan 77 dari 96 listing merupakan mobil tahun 2018 ke atas. Untuk memeriksa kewajarannya, harga setiap listing dibandingkan dengan median harga listing normal (di atas 5.000 SAR) dari merek, model, dan tahun yang sama. Agar median pembanding cukup stabil, perbandingan hanya dilakukan pada listing yang memiliki minimal 3 listing pembanding, yaitu sebanyak 54 listing.

Hasilnya, harga listing tersebut umumnya hanya sekitar 2% dari harga normal. Contohnya, Hyundai Elantra 2019 tercatat seharga 993 SAR, sedangkan median harga normal untuk model dan tahun yang sama adalah 50.250 SAR (dari 36 listing pembanding). Selisih sebesar ini tidak mungkin terjadi pada transaksi jual beli mobil, sehingga nilai tersebut tidak mencerminkan harga jual yang sebenarnya. Penyebab pastinya tidak dapat dipastikan dari data, namun kemungkinan berasal dari kesalahan input oleh penjual, misalnya mengisi nilai asal seperti 0 atau 1 pada kolom harga, atau salah ketik jumlah digit.

In [75]:
mid_price = priced[priced['Price'].between(5_000, 10_000, inclusive='left')]
mid_price = mid_price[['Make', 'Type', 'Year', 'Mileage', 'Price']]
mid_price.sort_values('Year', ascending=False).head(10)

           Make    Type  Year  Mileage   Price
6202       Fiat   Other  2013   180000  8500.0
3618  Chevrolet   Spark  2012   217912  9500.0
5294    Hyundai     i10  2012   172953  9000.0
3906     Nissan   Sunny  2011      290  7000.0
3902  Chevrolet   Optra  2011   216000  9000.0
2864      Honda   Other  2011     4200  6500.0
7192     Nissan   Sunny  2010   294000  9000.0
8087  Chevrolet   Optra  2010   206000  8000.0
4804  Chevrolet   Optra  2009   290000  7500.0
3784     Nissan  Altima  2009   400000  7500.0

In [76]:
print(f"Median Year    : {mid_price['Year'].median():.1f}")
print(f"Max Year       : {mid_price['Year'].max()}")
print(f"Median Mileage : {mid_price['Mileage'].median():,.0f} km")

# Pembanding: Chevrolet Optra tahun 2012 ke bawah
optra = priced[(priced['Type'] == 'Optra') & (priced['Year'] <= 2012)]
print(f"Median Price Optra (<= 2012): {optra['Price'].median():,.0f} SAR dari {len(optra)} listing")

Median Year    : 2004.5
Max Year       : 2013
Median Mileage : 216,956 km
Median Price Optra (<= 2012): 9,000 SAR dari 7 listing

Sebaliknya, listing pada rentang 5.000–10.000 SAR didominasi oleh mobil tua dengan jarak tempuh tinggi, dengan median tahun sekitar 2005 dan median jarak tempuh sekitar 217.000 km. Tidak ada satu pun listing di rentang ini yang merupakan mobil keluaran setelah tahun 2013. Harga-harga ini masih wajar untuk mobil berumur 8 tahun atau lebih, misalnya Chevrolet Optra 2010 seharga 8.000 SAR, yang sejalan dengan listing Optra lain di dataset (median 9.000 SAR untuk model tahun 2012 ke bawah). Dengan demikian, batas 5.000 SAR dapat digunakan untuk memisahkan harga yang tidak wajar dari harga yang wajar.

In [77]:
before = len(df)

# Drop listing dengan harga tidak wajar (< 5.000 SAR)
# Listing Negotiable (Price NaN) tetap dipertahankan
df = df[~(df['Price'] < 5_000)].reset_index(drop=True)

# Validasi
assert (df['Price'].dropna() >= 5_000).all(), "Masih ada Price < 5.000"
assert df['Price'].isna().sum() > 0, "Listing Negotiable ikut terhapus"
print(f"{before} -> {len(df)} baris ({before - len(df)} listing dihapus)")

8160 -> 8064 baris (96 listing dihapus)

Sebanyak **96 listing** dengan harga di bawah 5.000 SAR dihapus dari dataset. Berbeda dengan kolom fitur seperti `Mileage`, nilai tidak wajar pada `Price` tidak dapat diubah menjadi NaN lalu diimputasi, karena `Price` merupakan target yang akan diprediksi. Mengisi target dengan nilai hasil imputasi berarti model belajar dari harga buatan, bukan harga yang sebenarnya, sehingga baris-baris ini dihapus. Listing Negotiable tetap dipertahankan karena nilai kosongnya memang disengaja dan akan dipisahkan sebagai data inferensi. Jumlah data setelah penghapusan: 8.160 → **8.064 baris**.

Selain harga yang terlalu rendah, harga yang sangat tinggi juga diperiksa untuk memastikan tidak ada nilai yang tidak wajar di sisi atas distribusi.

In [78]:
priced = df[df['Price'].notna()]

priced.nlargest(10, 'Price')[['Make', 'Type', 'Year', 'Mileage', 'Price']]

             Make         Type  Year  Mileage      Price
1033     Mercedes            G  2021     5000  1150000.0
5933      Bentley     Bentayga  2019    13000   850000.0
3854     Mercedes            G  2019    60000   835000.0
4066     Mercedes            G  2019    39000   800000.0
3211      Bentley       Arnage  2020      300   772500.0
907       Bentley     Bentayga  2018    26000   750000.0
6720      Bentley     Bentayga  2018    20000   750000.0
3426     Mercedes            S  2021     2500   748000.0
4533   Land Rover  Range Rover  2020      100   700000.0
6381  Rolls-Royce        Ghost  2013    24000   700000.0

Sepuluh listing dengan harga tertinggi seluruhnya merupakan mobil mewah keluaran baru, seperti Mercedes G-Class, Bentley Bentayga, dan Rolls-Royce Ghost, dengan harga tertinggi 1.150.000 SAR. Harga-harga ini wajar untuk segmen mobil mewah, sehingga tidak dianggap sebagai anomali. Namun, harga yang tinggi tidak selalu terlihat janggal jika dilihat secara keseluruhan, sehingga perlu juga dibandingkan dengan harga listing lain dari model dan tahun yang sama.

In [79]:
group = priced.groupby(['Make', 'Type', 'Year'])['Price']

high_check = priced.copy()
high_check['Median_Group'] = group.transform('median')
high_check['N_Group'] = group.transform('size')
high_check['Ratio'] = (high_check['Price'] / high_check['Median_Group']).round(2)

# Listing dengan harga >= 2,5x median kelompoknya (minimal 3 listing per kelompok)
high_check[(high_check['N_Group'] >= 3) & (high_check['Ratio'] >= 2.5)][
    ['Make', 'Type', 'Year', 'Mileage', 'Price', 'Median_Group', 'N_Group', 'Ratio']
]

      Make      Type  Year  Mileage     Price  Median_Group  N_Group  Ratio
957   Ford  Explorer  2010    35000  160000.0       21000.0        5   7.62
3180  Ford      F150  2019    13339  291500.0      110000.0        3   2.65

Hasilnya, terdapat dua listing dengan harga jauh di atas listing lain dari model dan tahun yang sama. Ford Explorer 2010 tercatat seharga 160.000 SAR, sedangkan listing lain dengan model dan tahun yang sama berkisar 17.500–25.000 SAR. Selisih sekitar tujuh kali lipat ini kemungkinan berasal dari kesalahan input, misalnya kelebihan satu digit. Sementara itu, Ford F150 2019 seharga 291.500 SAR belum tentu salah, karena model ini memiliki varian dengan harga jauh lebih tinggi (misalnya F-150 Raptor), dan pembandingnya hanya 2 listing.

Berbeda dengan harga rendah, anomali pada sisi atas ini tidak dapat diidentifikasi dengan batas tetap, karena harga tinggi merupakan hal yang wajar untuk mobil mewah. Pemeriksaan per listing seperti di atas juga bergantung pada statistik data. Karena jumlahnya sangat sedikit dan dampaknya terhadap model kecil, listing-listing ini tidak dihapus dan dicatat sebagai keterbatasan data. Penanganan outlier yang lebih sistematis dapat dilakukan pada tahap modeling setelah train-test split.

#### **2.5.2 Column Mileage**

Kolom `Mileage` diperiksa menggunakan batas berdasarkan logika domain. Sebagai acuan, panduan dari Syarah menyebutkan bahwa jarak tempuh normal mobil di Arab Saudi berkisar 15.000–20.000 km per tahun, sedangkan jarak tempuh di bawah 1.000 km per tahun menandakan mobil jarang digunakan [1]. Pemeriksaan dilakukan pada dua sisi, yaitu jarak tempuh yang terlalu tinggi dan jarak tempuh yang terlalu rendah untuk umur mobilnya.

[1] Syarah, *Natural Mileage per Year*, https://syarah.com/carsguide/natural-mileage-per-year/

In [80]:
print(df['Mileage'].describe().round(0))

count        8064.0
mean       150443.0
std        347203.0
min           100.0
25%         38000.0
50%        103000.0
75%        197000.0
max      20000000.0
Name: Mileage, dtype: float64

Sebagian besar listing memiliki jarak tempuh yang wajar, dengan median sekitar 103.000 km dan 75% data berada di bawah 197.000 km. Namun, nilai maksimumnya mencapai 20.000.000 km, yang menunjukkan adanya nilai ekstrem di sisi atas.

In [81]:
high_mileage = df[df['Mileage'] > 1_000_000]
print(f"Mileage > 1,000,000 km: {len(high_mileage)} listing")

high_mileage = high_mileage.assign(
    Km_per_Year=(high_mileage['Mileage'] / (2021 - high_mileage['Year']).clip(lower=1)).round(0)
)
high_mileage[['Make', 'Type', 'Year', 'Mileage', 'Km_per_Year']].sort_values('Year')

Mileage > 1,000,000 km: 44 listing

            Make           Type  Year   Mileage  Km_per_Year
7298         GMC          C5700  1977   4358765      99063.0
4501    Mercedes   Short Bonnet  1983   9999999     263158.0
250       Toyota           Dyna  1987   1100000      32353.0
4529      Toyota       Cressida  1991   3000000     100000.0
4311         GMC       Suburban  1994   3700562     137058.0
6011   Chevrolet       Suburban  1997   2149656      89569.0
7558      Toyota          Camry  1998   4500000     195652.0
913       Nissan     Pathfinder  1998   3180003     138261.0
1583      Nissan     Pathfinder  2002   4090000     215263.0
2745   Chevrolet    Trailblazer  2004   3500000     205882.0
5632        Ford        Marquis  2005   2500000     156250.0
3432         GMC       Suburban  2005   4010000     250625.0
5561      Toyota   Land Cruiser  2006   4000000     266667.0
7161    Cadillac            DTS  2006   3000000     200000.0
4506      Toyota          Prado  2006   2800000     186667.0
2136   Chevrolet        Caprice  2007   3187031     227645.0
7713   Chevrolet          Tahoe  2007   1111111      79365.0
930    Chevrolet          Optra  2007   2000000     142857.0
7543     Mercury  Grand Marquis  2008   4000000     307692.0
7557        Ford        Marquis  2008   4000000     307692.0
6642      Toyota          Camry  2008   4430000     340769.0
803    Chevrolet          Tahoe  2008   3300000     253846.0
4259        Ford          Other  2008   1910000     146923.0
704       Nissan     Pathfinder  2008   3150000     242308.0
1242  Land Rover    Range Rover  2009   2013000     167750.0
7424   Chevrolet          Optra  2009  20000000    1666667.0
1825     Porsche        Cayenne  2009   3000000     250000.0
8051        Ford       Explorer  2010   3275230     297748.0
5010        Ford         Fusion  2010   3000000     272727.0
5091      Toyota         Aurion  2010   4900000     445455.0
905         Ford     Expedition  2010   2930000     266364.0
4580      Toyota        Corolla  2010   3500000     318182.0
7415      Toyota   Land Cruiser  2011   1060204     106020.0
4698   Chevrolet          Tahoe  2012   4691232     521248.0
4427      Toyota         Innova  2013   2211963     276495.0
6300      Toyota         Innova  2013   3640000     455000.0
4562       Mazda            CX9  2014   1700000     242857.0
7034     Hyundai         Sonata  2014   1500000     214286.0
7747   Chevrolet           Aveo  2014   1500000     214286.0
6321         Kia         Optima  2014   2002500     286071.0
3759     Hyundai        Elantra  2015   1600074     266679.0
6589        Ford     Expedition  2015   1330000     221667.0
7946      Toyota   Land Cruiser  2015   1500000     250000.0
6724     Hyundai          Azera  2018   1100000     366667.0

Terdapat **44 listing** dengan jarak tempuh di atas 1.000.000 km, setara dengan sekitar 50 tahun pemakaian normal. Sebagian besar merupakan mobil keluaran 2005–2018 (median tahun 2008), sehingga rata-rata jarak tempuhnya mencapai ratusan ribu km per tahun, jauh di atas pemakaian normal. Contohnya, Hyundai Azera 2018 tercatat 1.100.000 km, atau sekitar 367.000 km per tahun. Banyak di antaranya juga berupa angka bulat atau berpola, seperti 3.000.000, 4.000.000, 1.111.111, dan 9.999.999, yang lebih menyerupai isian asal dibandingkan hasil pembacaan odometer. Satu-satunya pengecualian yang masih mungkin wajar adalah Toyota Dyna 1987 (1.100.000 km), sebuah truk berumur 34 tahun dengan rata-rata sekitar 32.000 km per tahun, namun dampaknya kecil karena hanya satu listing.

In [82]:
old_low = df[(2021 - df['Year'] >= 5) & (df['Mileage'] < 1_000)]
print(f"Mobil >= 5 tahun dengan Mileage < 1,000 km: {len(old_low)} listing")
old_low['Mileage'].value_counts().head(10)

Mobil >= 5 tahun dengan Mileage < 1,000 km: 798 listing

Mileage
300    66
400    31
200    28
100    23
280    16
500    13
350    12
260    12
180    11
290    11
Name: count, dtype: int64

Di sisi lain, terdapat **798 listing** mobil berumur 5 tahun atau lebih dengan jarak tempuh di bawah 1.000 km, atau kurang dari 200 km per tahun. Angka ini jauh di bawah ambang "jarang digunakan" menurut panduan Syarah. Nilai yang paling sering muncul adalah angka bulat kecil seperti 300, 100, 400, dan 200, yang mengindikasikan penjual kemungkinan menuliskan jarak tempuh dalam satuan ribu km (misalnya 300 untuk 300.000 km). Namun, hal ini tidak dapat dipastikan, karena sebagian kecil mobil memang mungkin jarang digunakan.

In [83]:
before_nan = df['Mileage'].isna().sum()

invalid_mileage = (
    (df['Mileage'] > 1_000_000) |
    ((2021 - df['Year'] >= 5) & (df['Mileage'] < 1_000))
)
df.loc[invalid_mileage, 'Mileage'] = np.nan

# Validasi
assert (df['Mileage'].dropna() <= 1_000_000).all()
assert not ((2021 - df['Year'] >= 5) & (df['Mileage'] < 1_000)).any()
print(f"Mileage diubah menjadi NaN: {df['Mileage'].isna().sum() - before_nan} listing")
print(f"Jumlah baris tetap: {len(df)}")

Mileage diubah menjadi NaN: 842 listing
Jumlah baris tetap: 8064

Nilai `Mileage` yang tidak wajar pada kedua kelompok tersebut (total 842 listing) **diubah menjadi NaN**, bukan dibiarkan, dihapus barisnya, atau dikoreksi secara manual. Jika dibiarkan, model akan mempelajari angka yang salah, misalnya menganggap mobil dengan jarak tempuh 3.500.000 km sebagai mobil yang sangat sering dipakai, padahal angka tersebut hanya kesalahan input. Menghapus barisnya akan menghilangkan sekitar 10% data, padahal atribut lain pada baris-baris tersebut, termasuk merek, model, tahun, dan harga, masih valid dan berguna bagi model. Sementara itu, mengoreksi nilainya secara manual (misalnya mengalikan 300 menjadi 300.000 km) hanya berdasarkan dugaan yang tidak dapat dipastikan, sehingga berisiko memasukkan data yang keliru.

Dengan mengubahnya menjadi NaN, nilai yang tidak dapat dipercaya dibuang tanpa kehilangan informasi lain pada baris yang sama. Nilai kosong ini akan diimputasi pada tahap modeling setelah train-test split, bersama nilai kosong pada kolom lain yang telah diidentifikasi di bagian 2.4, misalnya menggunakan median `Mileage` dari mobil dengan tahun yang sama pada data train, karena jarak tempuh sangat bergantung pada umur mobil. Pendekatan ini juga memudahkan penanganan data baru saat model digunakan. Jika suatu saat terdapat listing baru dengan jarak tempuh tidak wajar, misalnya di atas 1.000.000 km, aturan yang sama dapat langsung diterapkan: nilainya diubah menjadi NaN lalu diimputasi oleh pipeline. Sebaliknya, jika baris tersebut dihapus saat training, perlu ada aturan terpisah untuk menangani input seperti itu, misalnya dengan menolaknya, karena model tidak pernah mempelajari kasus serupa.

Batas yang digunakan (di atas 1.000.000 km, serta di bawah 1.000 km untuk mobil berumur 5 tahun atau lebih) ditentukan berdasarkan logika domain, bukan dihitung dari distribusi data. Oleh karena itu, penanganan ini aman dilakukan sebelum train-test split tanpa menimbulkan data leakage.

## **Section 3. Save Clean Data**

In [84]:
import os

before = len(df)

df_negotiable = df[df['Price'].isna()].drop(columns='Price').reset_index(drop=True)
df_clean = df[df['Price'].notna()].reset_index(drop=True)
df_clean['Price'] = df_clean['Price'].astype(int)

assert len(df_clean) + len(df_negotiable) == before
assert df_clean['Price'].isna().sum() == 0
assert df_clean['Price'].dtype == 'int64'
assert (df_clean['Price'] >= 5_000).all()
assert df_clean['Mileage'].dropna().le(1_000_000).all()

print(f"df_clean      : {df_clean.shape}")
print(f"df_negotiable : {df_negotiable.shape}")

os.makedirs('../data/processed', exist_ok=True)
df_clean.to_csv('../data/processed/cars_clean.csv', index=False)
df_negotiable.to_csv('../data/processed/cars_negotiable.csv', index=False)

df_clean      : (5487, 12)
df_negotiable : (2577, 11)

Setelah seluruh proses pembersihan selesai, dataset dipisahkan menjadi dua bagian berdasarkan ketersediaan harga. Sebanyak 5.487 listing yang memiliki harga disimpan sebagai `df_clean` dan akan digunakan untuk EDA serta pelatihan dan evaluasi model. Sementara itu, 2.577 listing berstatus Negotiable disimpan terpisah sebagai `df_negotiable` tanpa kolom Price. Listing ini tidak dapat digunakan untuk training maupun testing karena tidak memiliki target, tetapi dapat dimanfaatkan sebagai data inferensi untuk memperkirakan harga wajar mobil yang dijual tanpa mencantumkan harga.

Kolom Price pada `df_clean` diubah menjadi tipe integer karena sudah tidak mengandung nilai kosong dan seluruh harga dalam satuan riyal tanpa desimal. Nilai kosong pada kolom fitur seperti Engine_Size, Mileage, Options, Origin, dan Gear_Type sengaja dibiarkan, karena akan diimputasi di dalam pipeline setelah train-test split agar tidak terjadi data leakage. Kedua dataset disimpan ke folder `data/processed` supaya bisa langsung digunakan di notebook berikutnya tanpa mengulang proses data preparation.